media:
  - name: serviceImages
    label: ServiceImages
    input: data/services/images
    output: data/services/images
    
  - name: galleryImages
    label: GalleryImages
    input: data/gallery
    output: data/gallery

  - name: companyImages
    label: CompanyImages
    input: data/company
    output: data/company
    
content:
  - name: company
    label: Company
    type: file
    path: data/company/company.json
    format: json
    list: true
    fields:
      - name: companyName
        label: CompanyName
        type: string
      - name: logo
        label: Logo
        type: image
      - name: yearStarted
        label: YearStarted
        type: number
      - name: tagline
        label: TagLine
        type: string
      - name: description
        label: Description
        type: text
      - name: about
        label: About
        type: text
      
  - name: services
    label: Services
    type: file
    path: data/services/services.json
    format: json
    list: true

    fields:
      - name: title
        label: Service Name
        type: string

      - name: description
        label: Description
        type: text

      - name: price
        label: Price
        type: string

      - name: link
        label: Link
        type: string

      - name: paymentLink
        label: PaymentLink
        type: string

      - name: image
        label: Image
        type: image

      - name: video
        label: Video
        type: string

  - name: gallery
    label: Gallery
    type: file
    path: data/gallery/gallery.json
    format: json
    list: true

    fields:
      - name: src
        label: Image
        type: image

      - name: alt
        label: Alt
        type: string
